### ISSUE TITLE
Stick Font " Unknown Rotation" error

### ISSUE THREAD

**Issue by BewilderedAgain** [pstemari/v-engrave-plugin#23]
Using Cambam 0.9.8 on WIn 10 64bit
Simple test drawing with only Cambam stick font 3 gives me errors when I try to generate the toolpaths.  The toolpaths are also, wrong.  See attached.
![Toolpaths](https://user-images.githubusercontent.com/21289886/62063264-74387500-b222-11e9-98a8-fe7136501a76.JPG)
![Errors](https://user-images.githubusercontent.com/21289886/62063271-76023880-b222-11e9-89a0-50ca2a8f0951.JPG)

[TestText.zip](https://github.com/pstemari/v-engrave-plugin/files/3443138/TestText.zip)

**Comment by pstemari** [comment]
Without taking a look at it in detail, I imagine that the problem is that you're using a stick font and not a regular font. The way the V engrave plug-in works is that it tracks along the inside edge of the font outline and varies the depth in order to reach the opposite side of the front stroke. A true stick font would have zero width, and thus zero depth, but would in all likelihood get some sort of a math error. 


Give it a try with something like Times New Roman or Helvetica. 


—Paul 


On Jul 29, 2019 9:02 AM, BewilderedAgain <notifications@github.com> wrote: 

Using Cambam 0.9.8 on WIn 10 64bit
Simple test drawing with only Cambam stick font 3 gives me errors when I try to generate the toolpaths. The toolpaths are also, wrong. See attached.
 
 

TestText.zip

**Comment by BewilderedAgain** [comment]
Yes, Paul, that was the issue.  Thanks.
